# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  SONAR_HOST_URL: 'http://81.19.214.94:9000/'
  SONAR_PROJECT_KEY: 'test-public-repo'

steps:

- script: |
    sudo apt update
    sudo apt install -y openjdk-17-jdk maven git curl
    java -version
    mvn -version
  displayName: 'Install Java & Maven'

- script: |
    git clone https://github.com/spring-projects/spring-petclinic.git
    cd spring-petclinic
    mvn clean install -DskipTests
  displayName: 'Build Project (Generate .class files)'

- script: |
    cd spring-petclinic
    mvn sonar:sonar \
      -Dsonar.projectKey=$(SONAR_PROJECT_KEY) \
      -Dsonar.host.url=$(SONAR_HOST_URL) \
      -Dsonar.login=$(SONAR_TOKEN)
  env:
    SONAR_TOKEN: $(SONAR_TOKEN)
  displayName: 'Run SonarQube Scan'